version: '4.2.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:8000
    depends_on:
      - mongo_db
    volumes:
      - .:/app
      - public-data:/app/public
    networks:
      - app
    command: ['npm', 'run', 'start:dev']

  mongo_db:
    image: mongo 
    restart: always
    networks:
      - app
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - db:/data/db

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mongo_db
    environment:
      ADMINER_DEFAULT_SERVER: mongo_db
    ports:
      - 8080:8080
    networks:
      - app

volumes:
  app:
  db:
  public-data:

networks:
  app:
    driver: bridge
